apiVersion: v1
data:
  config.json: |-
    {
      "inbounds": [
        {
          "port": {{ .Values.v2ray.port }},
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": "{{ default (uuidv4) .Values.v2ray.client_id }}",
                "alterId": 0
              }
            ]
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
kind: ConfigMap
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}