apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fullname }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fullname }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullname }}
    spec:
      containers:
        - name: v2ray
          image: v2fly/v2fly-core:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.v2ray.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/v2ray/config.json
              subPath: config.json
          livenessProbe:
            tcpSocket:
              port: {{ .Values.v2ray.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: {{ .Values.v2ray.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          command: ["v2ray"]
          args: ["run", "-c", "/etc/v2ray/config.json"]
      volumes:
        - name: config
          configMap:
            name: {{ .Values.fullname }}
