apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fullname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.fullname }}
  ports:
    - name: v2ray
      port: {{ .Values.v2ray.port }}
      targetPort: {{ .Values.v2ray.port }}
      protocol: TCP
      nodePort: {{ .Values.v2ray.port }}
